# Generated by Django 3.2.9 on 2021-11-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=150)),
                ('caseowner', models.CharField(max_length=100)),
            ],
        ),
    ]
