# Generated by Django 3.2.9 on 2021-11-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='caseowner',
        ),
        migrations.AddField(
            model_name='ticket',
            name='source',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='ticket',
            name='target',
            field=models.CharField(default='', max_length=99),
        ),
    ]
